(in-package :cavern-chronicle)

(defun play ()
  (let ((window-width 640)
	(window-height 480))
    (sdl2:with-init (:everything)
      (sdl2-ttf:init)
      (sdl2:with-window (window :w window-width :h window-height :flags '(:shown :opengl))
	(sdl2:with-renderer (renderer window :flags '(:accelerated))
	  (sdl2:with-event-loop (:method :poll)
        (:keydown (:keysym keysym)
                  (print keysym))
        (:keyup (:keysym keysym)
                (when (sdl2:scancode= (sdl2:scancode-value keysym) :scancode-escape)
                  (sdl2:push-event :quit)))
        (:idle ()
               (sdl2:set-render-draw-color renderer 40 40 40 255)
               (sdl2:render-clear renderer)
               (sdl2:render-present renderer))
        (:quit () t)))))))
